node{
	def commit_id
  def azurekubernetesCredentials = 'azure_kubernetes_credentials'
  def DOCKERHUB_CREDENTIALS = 'dockerhub_credentials'
  def webappReleaseName = "webapp"
  def webapp_DB_Credentials = "azure_webapp_db_credentials"


	stage('Git Clone') {
		checkout scm
	}

  stage('Build docker image') {
  commit_id = sh(returnStdout: true, script: 'git rev-parse HEAD')
  commit_id = sh(returnStdout: true, script: """echo $commit_id . """).trim()
  dockerImage = docker.build ("${env.BACKEND_IMAGE_WEBAPP}")
  }
		
    
  stage('Push image') {
          docker.withRegistry( '', DOCKERHUB_CREDENTIALS ) {
          dockerImage.push("$commit_id")
          dockerImage.push("latest")
      }
  }

  stage('Startup activities'){
  echo "${env.AZURE_KUBERNETES_API}"
  withKubeConfig([credentialsId: azurekubernetesCredentials,
                      serverUrl: "${env.AZURE_KUBERNETES_API}"
                      ]) {
        sh "kubectl cluster-info"
  }

  }

  stage('Continous Deployment Helm Upgrade'){
  
  withKubeConfig([credentialsId: azurekubernetesCredentials,
                      serverUrl: "${env.AZURE_KUBERNETES_API}"
                      ]) {
        sh "helm version"
        sh "pwd"
        sh "ls -a"
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: webapp_DB_Credentials,
    usernameVariable: 'DBUSERNAME', passwordVariable: 'DBPASSWORD']]) {
      withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: DOCKERHUB_CREDENTIALS,
    usernameVariable: 'DOCKERUSERNAME', passwordVariable: 'DOCKERPASSWORD']]) {
        sh("helm upgrade webapp ./helm/webapp-helm/ --set DB_USERNAME=$DBUSERNAME,DB_PASS=$DBPASSWORD,DB_HOST_WEBAPP=${AZURE_DB_HOST_WEBAPP},imageCredentials.Docker_username=$DOCKERUSERNAME,imageCredentials.Docker_password=$DOCKERPASSWORD,webappDockerImage=${BACKEND_IMAGE_WEBAPP}:$commit_id,webappIngress.domainName=${AZURE_WEBAPP_DOMAIN},webappIngress.subDomainName=${AZURE_WEBAPP_SUB_DOMAIN}")
    }
    }
  }
  }


}
